Networking_Project/Controllers/GuestController.cs
using Networking_Project.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace Networking_Project.Controllers
{
    public class GuestController : Controller
    {
        // GET: Guest

        private DATABASEEntities db = new DATABASEEntities();
       
        public ViewResult Index(string sortOrder, string currentFilter, string cF1, string cF2,
           string searchCategory, string searchPriceR1, string searchPriceR2, string searchDateR1,
           string searchDateR2, string cF3, string cF4, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CategorySortParm = String.IsNullOrEmpty(sortOrder) ? "category_desc" : "";
            ViewBag.TicketPriceSortParm = sortOrder == "TicketPrice" ? "ticketprice_desc" : "TicketPrice";
            ViewBag.RankSortParm = sortOrder == "Rank" ? "rank_desc" : "Rank";
            if (searchCategory != null)
            {
                page = 1;
            }
            else
            {
                if (searchCategory == null)
                { searchCategory = currentFilter; }
                else if (searchPriceR1 == null && searchPriceR2 == null)
                {
                    searchPriceR1 = cF1;
                    searchPriceR2 = cF2;
                }
                else if (searchDateR1 == null && searchDateR2 == null)
                {
                    searchDateR1 = cF3;
                    searchDateR2 = cF4;
                }
                else { page = 1; }
            }

            ViewBag.CurrentFilter = searchCategory;
            ViewBag.cF1 = searchPriceR1;
            ViewBag.cF2 = searchPriceR2;
            ViewBag.cF3 = searchDateR1;
            ViewBag.cF4 = searchDateR2;
            var movies = from s in db.MoviesTbl
                         select s;
            if (!String.IsNullOrEmpty(searchCategory) || !String.IsNullOrEmpty(searchPriceR1) &&
                !String.IsNullOrEmpty(searchPriceR2) ||
                !String.IsNullOrEmpty(searchDateR1) && !String.IsNullOrEmpty(searchDateR2))
            {
                if (!String.IsNullOrEmpty(searchCategory))
                {
                    movies = movies.Where(s => s.Category.Contains(searchCategory)
                                         || s.Category.Contains(searchCategory));
                }
                else if (!String.IsNullOrEmpty(searchDateR1) && !String.IsNullOrEmpty(searchDateR2))
                {
                    var dt1 = DateTime.Parse(searchDateR1);
                    var dt2 = DateTime.Parse(searchDateR2);
                    movies = movies.Where(s => s.StartTime >= dt1 && s.StartTime <= dt2);
                }
                else
                {

                    var pricerange1 = Int32.Parse(searchPriceR1);
                    var pricetrange2 = Int32.Parse(searchPriceR2);
                    movies = movies.Where(s => s.TicketPrice >= pricerange1 && s.TicketPrice <= pricetrange2);
                }
            }
            switch (sortOrder)
            {
                case "category_desc":
                    movies = movies.OrderByDescending(s => s.Category);
                    break;
                case "TicketPrice":
                    movies = movies.OrderBy(s => s.TicketPrice);
                    break;
                case "ticketprice_desc":
                    movies = movies.OrderByDescending(s => s.TicketPrice);
                    break;
                case "Rank":
                    movies = movies.OrderBy(s => s.Rank);
                    break;
                case "rank_desc":
                    movies = movies.OrderByDescending(s => s.Rank);
                    break;
                default:
                    movies = movies.OrderByDescending(s => s.Category);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(movies.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult PayMent()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PayMent(int id,int iduser,OrdersTbl ord)
        {
            DateTime localDate = DateTime.Now;
            string text = "This film has already been screened!!!";
            MoviesTbl movie = db.MoviesTbl.Find(id);
            if (movie.StartTime <= localDate)
            {
                MessageBox.Show(text);
                return RedirectToAction("Index");
            }
            ord.idScreen = id;
            ord.idUser = iduser;
            ord.Pay = true;
            ord.Status = "A ticket was purchased";
            if (Order_(ord))
            {
                var check_occupied = db.OrdersTbl.FirstOrDefault(s => s.idScreen == ord.idScreen &&
                s.Chair == ord.Chair && ord.Pay == true);
                var check_pay = db.OrdersTbl.FirstOrDefault(s => s.idScreen == ord.idScreen &&
              s.Chair == ord.Chair && ord.Pay == false);

                if (check_occupied == null && ord.Chair >= 1 && ord.Chair <= movie.NumberSeats
                   )
                {
                    db.OrdersTbl.Add(ord);
                    if(check_pay!=null)
                    {
                        OrdersTbl ord_new = new OrdersTbl
                        {
                            //idOrder = order_check.idOrder,
                            idUser = check_pay.idUser,
                            idScreen = check_pay.idScreen,
                            Chair = check_pay.Chair,
                            Pay = false,
                            Status = "out of stock",
                            NumberCard = 000000,
                            Validity = localDate,
                            validation = 0
                        };
                        int id_ = check_pay.idOrder;
                        OrdersTbl ordd_ = db.OrdersTbl.Find(id_);
                        db.OrdersTbl.Remove(ordd_);
                        db.OrdersTbl.Add(ord_new);
                    }
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    if (check_occupied != null)

                    {
                        MessageBox.Show("its seat already occupied!!! choose another seat");
                        //ViewBag.ErrorMessage = ("its seat already occupied!!! choose another seat");


                    }
                    if (ord.Chair <= 1 || ord.Chair >= movie.NumberSeats)
                    {
                        MessageBox.Show("Invalid seat!!! choose seat between 1 - " + movie.NumberSeats);
                        //ViewBag.error = "Invalid seat!!! choose seat between 1-" + movie.NumberSeats;

                    }
                    return View(ord);
                }
            }
            return View(ord);
        }
        public bool Order_(OrdersTbl ord)
        {
            if (ModelState.IsValid)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
}

Networking_Project/Controllers/HomeController.cs
using Networking_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace Networking_Project.Controllers
{
    public class HomeController : Controller
    {
        private DATABASEEntities _db = new DATABASEEntities();
        //GET: Register

        public ActionResult Register()
        {
            return View();
        }

        //POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(UsersTbl _user)
        {
            if (ModelState.IsValid)
            {
                var check = _db.UsersTbl.FirstOrDefault(s => s.Email == _user.Email);
                if (check == null)
                {
                    _db.UsersTbl.Add(_user);
                    _db.SaveChanges();
                    return RedirectToAction("Login");
                }
                else
                {
                    MessageBox.Show("Email already exists");
                    return View();
                }


            }
            return View();


        }

        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email, string password)
        {
            if (ModelState.IsValid)
            {
                var data = _db.UsersTbl.Where(s => s.Email.Equals(email) && s.Password.Equals(password)).ToList();
                if (data.Count() > 0)
                {
                    //add session
                    Session["FullName"] = data.FirstOrDefault().FirstName + " " + data.FirstOrDefault().LastName;
                    Session["Email"] = data.FirstOrDefault().Email;
                    Session["idUser"] = data.FirstOrDefault().idUser;
                    string id = Session["idUser"].ToString();
                    if (Session["idUser"] != null)
                    {
                        if (id == "1")
                        {
                            return RedirectToAction("Index", "Admin");
                        }
                        else
                        {
                            return RedirectToAction("Index", "Users");
                        }
                    }
                   
                }
                else
                {
                    MessageBox.Show("Login failed");
                    return RedirectToAction("Login");
                }
            }
            return View();
        }


        //Logout
        public ActionResult Logout()
        {
            Session.Clear();//remove session
            return RedirectToAction("Login");
        }



       

    }
}

Networking_Project/Views/Home/Login.cshtml
@model Networking_Project.Models.UsersTbl

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
               
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-primary" value="Login" />
                        <a href="@Url.Action("Register","Home")" class="btn btn-warning"> Don't have an account yet? Create now!</a>
                        <a href="@Url.Action("Index","Guest")" class="btn btn-warning"> Do you want try guest stauts? Try now!</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Networking_Project/Views/Home/Register.cshtml
@model Networking_Project.Models.UsersTbl

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row justify-content-md-center">
    <div class="col-md-5">
        @using (Html.BeginForm("Register", "Home", FormMethod.Post))
        {
            //@Html.ValidationSummary()
            @Html.AntiForgeryToken()

            <div class="card">
                <div class="card-header">
                    <div class="card-title">Register</div>
                </div>
                <div class="card-body">
                    <div class="form-group">
                        @Html.LabelFor(m => m.FirstName)
                        @Html.TextBoxFor(m => m.FirstName, "", new { @class = "form-control", @placeholder = "First Name" })
                        @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.LastName)
                        @Html.TextBoxFor(m => m.LastName, "", new { @class = "form-control", @placeholder = "Last Name" })
                        @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "badge badge-danger" })

                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "badge badge-danger" })
                        @if (ViewBag.error != null)
                        {
                            <span class="badge badge-danger">@ViewBag.error</span>
                        }
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                        @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.ConfirmPassword)
                        @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", @placeholder = "Confim Password" })
                        @Html.ValidationMessageFor(m => m.ConfirmPassword, "", new { @class = "badge badge-danger" })
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn btn-danger" value="Register" />
                        <a href="@Url.Action("Login","Home")" class="btn btn-warning"> Do you have account ? Enter now!</a>
                        <a href="@Url.Action("Index","Guest")" class="btn btn-warning"> Do you want try status guest ? try now!</a>
                        
                    </div>
                </div>
            </div>

        }
    </div>
</div>